# API Documentation Generation Configuration File
# This file defines various parameters and options for documentation generation

# Exclusion pattern configuration
exclude_patterns:
  - "__pycache__"
  - ".venv"
  - "venv"
  - ".git"
  - ".pytest_cache"
  - "node_modules"
  - "tests"
  - "test"
  - "ipynb"
  - "dist"
  - "build"
  - "site-packages"

# Specific files to exclude
exclude_files:
  - "__main__.py"
  - "setup.py"
  - "conftest.py"
  - "version.py"

# List of package directories to process
packages:
  - name: "bridgic-core"
    path: "bridgic-core"
    description: "Bridgic Core"

# Documentation generation options
generation_options:
  # Base path for documentation generation
  docs_base_path: "reference"
  
  # Whether to generate verbose logs
  verbose: true
  
  # Whether to skip empty modules
  skip_empty_modules: true
  
  # Whether to show source code
  show_source: true
  
  # Whether to show root heading (module-level). We prefer starting at class level.
  show_root_heading: false
  
  # Whether to show root toc entry (module-level link in toc)
  show_root_toc_entry: false
  
  # Whether to generate index pages
  generate_index_pages: true
  # Only generate index pages (from __init__.py) and skip module pages
  only_index_pages: true
  # Render single-entry packages as groups with Index child in nav (ensures visibility)
  single_entry_as_group: true
  
  # Docstring style (numpy, google, sphinx)
  docstring_style: "numpy"

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(levelname)s - %(message)s"
  
# Advanced options
advanced_options:
  # Whether to process type annotations
  process_type_annotations: true
  
  # Whether to generate cross-references
  generate_cross_references: true
  
  # Maximum recursion depth
  max_recursion_depth: 10
  
  # Parallel processing
  enable_parallel_processing: false
  
  # Caching settings
  enable_caching: false
