name: Sync main to dev

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write

jobs:
  merge:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub App token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.CI_BOT_APP_ID }}
          private_key: ${{ secrets.CI_BOT_APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - name: Configure Git
        run: |
          git config user.name "bitsky-ci[bot]"
          git config user.email "bitsky-ci[bot]@users.noreply.github.com"

      - name: Sync main to dev
        run: |
          git fetch origin dev
          git checkout dev
          git merge origin/main -m "Sync: auto merge main after merging ${{ github.event.pull_request.head.ref }}."
          git push origin dev
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
